### ISSUE TITLE
Pet Data

### ISSUE THREAD

**Issue by gururaj3** [gcivil-nyu-org/match-a-pet#26]
@Peter-S-G and @shrutiagarwal28  - 

1. Work on to get our data for the pets to be created
2. Work on to see how we can create this data for the future in an easy and fast manner
3. Look if we can possibly scrape the data or if the data is readily available on the internet 
4. Make sure the fields that we have appropriate fields in the data and not redundant data

**Comment by shrutiagarwal28** [comment]
-For the purpose of this sprint and upcoming initial sprints, we should go with using sample dummy data.
-This is acceptable because the primary goal of the web-app is based on Shelter Staff/Volunteers uploading pet profiles for animals who can be adopted and then keep people updated about them through social media posts.
-Web scraping to populate database should be a secondary thing that can be thought of later after completion of main Product Backlogs as that will only create an incomplete Pet Profile and does not align with the product goal.

**Comment by shrutiagarwal28** [comment]
-I have created the excel sheet with the requisite fields and have marked the not-null fields with a star.
-Request @Peter-S-G to please populate the sheet that acts as the sample pet profile database which is to be used for testing purposes.
-Sheet link is : https://docs.google.com/spreadsheets/d/1pOUqucN3j0OBOXOXhjwTCk4XMXI13LGTmSfGq4Q9GSc/edit?usp=sharing
- Editing rights available to everyone on the team; request discussion before editing fields.

**Current fields:**
 ID No. *	
Animal Type *
Name
Picture *	
Color*	
Sex (M/F) (This field is not marked compulsory as it is difficult to figure sex for certain animals)	
Breed(if known)	
Age (if known)	
Spayed/Neutered (Y/N)
Shelter (Location) *	
Caretaker * (this is the guy who uploads the profile)

**Comment by shrutiagarwal28** [comment]
- Issue completed on my end

**Comment by shrutiagarwal28** [comment]
@Peter-S-G: DB has 30-40 entries for cats and dogs. 
- Will review whether we need to add more animals later into course
