### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by benji7890** [gcivil-nyu-org/match-a-pet#34]
**User story**

As a user, I should be able to register an account on Match a Pet.

**Acceptance criteria**

-User registration page should have unique username
-User can add any display name
-User should be able to register with email
-User should be able to have a password with password checks in place

**Not Acceptance criteria**
-User should be able to add profile photo
-User should be allowed to write a Bio in a few lines for themselves
-User should be able to add their age and gender
-User should be able to select their interests

**Definition of Done**

-User profile is getting added to the the User database with the following entries: Username, name, email, password

**Pointing Poker Score**

3

**Comment by shrutiagarwal28** [comment]
Update: Acceptance criteria and definition of done added

**Comment by shrutiagarwal28** [comment]
A bug in the migrations leads to SQLite not being correctly created

**Comment by shrutiagarwal28** [comment]
**Progress Update:**

-Traced back error and realized that it is because we can have only one User Model in Django. 
- Current User model is designed for shelter staff and also contains the fields Shelter City and Shelter State which we do not need for a regular user.

**Possible Fixes:**
1. To accommodate multiple user types we can have the Custom User Model extended such that it has Shelter User type and (Regular) User type. 
Since the regular user has the basic/universal fields-email and password, it makes more sense to keep those in the superuser and extend model to include shelter fields.

2. Another, not very efficient (redundant from DB point of view) but doable, fix would be to keep using the current custom user model and have the shelter specific fields nullified for regular users. This will lead us to having both Shelter users and Regular Users entered in the same database initially with the Shelter City and Shelter State fields nullified. 
To separate the user types we can modify the model to take binary value input for 'isStaff/isUser' and then separate the two users based on that.

@shornbuckle you might want to have a look at this as a point to explain during our sprint demo.
