### ISSUE TITLE
Get pop-up/hover functionality to work on the UI for login

### ISSUE THREAD

**Issue by shornbuckle** [gcivil-nyu-org/match-a-pet#44]
Counting Poker Score of 2

User Story:
As a user, I should be able to hover or click on Login and Register to have a pop-up appear containing the respective fields where I can enter my credentials.

Acceptance criteria:
1. On hovering or clicking on the login button, a pop-up  should appear that contains the fields username and password should appear for the user to login
2. On hovering or clicking on the shelter login button, a pop-up  should appear that contains the fields for shelter staff login
3. Clicking Login button in the popup  should redirect to user's personal home page

Definition of done:
- Pop up should appear when login button is clicked or hovered upon
- Login Button within Pop-up should redirct to personal home-page

**Comment by shrutiagarwal28** [comment]
Progress Update:

- Appearance of pop-up made to be on-click instead of hover as css-class settings of the fixed nav-bar make it very difficult to have things overlay on top of it.
- Functional Login-popup on front-end presented to the team. 
- Login-popup for user could not be connected to user database as current Custom-user model exists only for shelter staff and not has not been extended for users yet.
- Pop-up design discarded temporarily in order to maintain design consistency and replaced with dropdown menu for User and staff login that redirects to corresponding web-page.
